from __future__ import annotations

import json
import re
from typing import Any, Dict, List


def _clean(value: Any) -> Any:
    """Convert nested BioFlow structures into JSON-safe values."""
    if isinstance(value, dict):
        return {str(k): _clean(v) for k, v in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [_clean(v) for v in value]
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    return str(value)


def _candidate_rows(step: Dict[str, Any]) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []

    tools = step.get("tools") or []
    if isinstance(tools, list):
        for tool in tools:
            if not isinstance(tool, dict):
                continue
            row = {
                "id": tool.get("id"),
                "name": tool.get("name") or tool.get("id"),
                "description": tool.get("description", ""),
            }
            score = tool.get("score")
            if isinstance(score, dict):
                if score.get("total") is not None:
                    row["bioflow_score"] = score.get("total")
                elif score.get("score") is not None:
                    row["bioflow_score"] = score.get("score")
            rows.append(row)

    if rows:
        return rows

    candidates = step.get("candidates") or []
    if not isinstance(candidates, list):
        candidates = [candidates]

    return [
        {"id": item, "name": str(item)}
        for item in candidates
        if item
    ]


def workflow_export_payload(workflow: Dict[str, Any]) -> Dict[str, Any]:
    steps_out: List[Dict[str, Any]] = []

    for number, step in enumerate(workflow.get("steps", []) or [], start=1):
        if not isinstance(step, dict):
            continue
        steps_out.append(
            {
                "number": number,
                "name": step.get("name", f"Step {number}"),
                "operation": step.get("operation"),
                "description": step.get("description", ""),
                "mode": step.get("mode", "sequential"),
                "candidate_tools": _candidate_rows(step),
            }
        )

    payload = {
        "schema_version": 1,
        "generated_by": "BioFlow",
        "workflow": {
            "id": workflow.get("id"),
            "name": workflow.get("name", "BioFlow workflow"),
            "description": workflow.get("description", ""),
            "context": workflow.get("context", {}) or {},
            "external_inputs": workflow.get("external_inputs", []) or [],
            "steps": steps_out,
        },
    }
    return _clean(payload)


def workflow_to_json(workflow: Dict[str, Any]) -> str:
    return json.dumps(
        workflow_export_payload(workflow),
        ensure_ascii=False,
        indent=2,
        sort_keys=False,
    )


def workflow_to_markdown(workflow: Dict[str, Any]) -> str:
    payload = workflow_export_payload(workflow)["workflow"]
    lines: List[str] = [
        f"# {payload['name']}",
        "",
        "Generated by BioFlow.",
        "",
    ]

    if payload.get("description"):
        lines.extend([payload["description"], ""])

    context = payload.get("context") or {}
    if context:
        lines.extend(["## Dataset context", ""])
        for key, value in context.items():
            if value is None or value == "":
                continue
            label = str(key).replace("_", " ").strip().title()
            lines.append(f"- **{label}:** {value}")
        lines.append("")

    external_inputs = payload.get("external_inputs") or []
    if external_inputs:
        lines.extend(["## Required inputs", ""])
        for item in external_inputs:
            lines.append(f"- {str(item).replace('_', ' ')}")
        lines.append("")

    lines.extend(["## Workflow steps", ""])
    for step in payload.get("steps", []):
        lines.append(f"### {step['number']}. {step['name']}")
        lines.append("")
        if step.get("description"):
            lines.extend([step["description"], ""])
        if step.get("operation"):
            lines.append(f"**Operation:** `{step['operation']}`")
            lines.append("")

        candidates = step.get("candidate_tools") or []
        if candidates:
            lines.append("**Candidate tools:**")
            for tool in candidates:
                name = tool.get("name") or tool.get("id") or "Tool"
                score = tool.get("bioflow_score")
                suffix = f" — BioFlow score {score}/100" if score is not None else ""
                lines.append(f"- {name}{suffix}")
            lines.append("")

    lines.extend(
        [
            "---",
            "",
            "BioFlow recommendations should be interpreted together with the "
            "dataset-specific suitability checks shown in the application.",
            "",
        ]
    )
    return "\n".join(lines)


def export_filename(workflow: Dict[str, Any], extension: str) -> str:
    raw = workflow.get("name") or workflow.get("id") or "bioflow_workflow"
    slug = re.sub(r"[^A-Za-z0-9]+", "_", str(raw)).strip("_").lower()
    if not slug:
        slug = "bioflow_workflow"
    return f"{slug}.{extension.lstrip('.')}"
